name:                guardian
version:             0.4.0.0
license:             BSD-3-Clause
author:              "DeepFlow, Inc."
maintainer:          "DeepFlow, Inc."
copyright:           "(c) 2021-2023, DeepFlow, Inc."
github:              deepflowinc/guardian

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            The border guardian for your package dependencies
category:            Development

description: 
  Guardian secures your Haskell monorepo package dependency boundary.
  Please read [README.md](https://github.com/deepflowinc/guardian#readme) for more details.


ghc-options:
- -Wall

data-dir: data

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src
  dependencies:
  - aeson
  - algebraic-graphs
  - array
  - Cabal
  - Cabal-syntax
  - cabal-install >= 3.8
  - case-insensitive
  - containers
  - dlist
  - generic-lens
  - githash
  - hashable
  - indexed-traversable
  - indexed-traversable-instances
  - language-dot
  - microlens
  - optparse-applicative
  - parsec
  - path
  - path-io
  - rio
  - selective
  - semigroups
  - stack >= 2.9
  - template-haskell
  - transformers
  - typed-process
  - unordered-containers
  - validation-selective
  - vector
  - yaml

tests:
  guardian-test:
    main: Spec.hs
    source-dirs: test
    build-tools:
    - tasty-discover
    dependencies:
    - algebraic-graphs
    - bytestring
    - containers
    - guardian
    - path
    - path-io
    - rio
    - tasty
    - tasty-hunit
    - text
    - unordered-containers
    - validation-selective

executables:
  guardian:
    source-dirs: app
    main: Main.hs
    dependencies:
    - guardian
